ALTER TABLE users
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE products
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE orders
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE order_item
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE payments
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE shipments
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE carts
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE galleries
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;